# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: {{ .Values.django.config.debug | quote }}
  DB_HOST: {{ .Values.django.config.dbHost | quote }}
  DB_PORT: {{ .Values.django.config.dbPort | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.config.allowedHosts | quote }}
  ENVIRONMENT: {{ .Values.django.config.environment | quote }}