apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app: django
  ports:
    - protocol: TCP
      port: {{ .Values.django.service.port }}  
      targetPort: {{ .Values.django.service.targetPort }}
      