apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: {{ .Values.django.service.type | quote }}
  selector:
    app: django
  ports:
    - protocol: TCP
      port: {{ .Values.django.service.port | quote }}
      targetPort: {{ .Values.django.service.targetPort | quote }}
      {{- if eq .Values.django.service.type "NodePort" }}
      nodePort: {{ .Values.django.service.nodePort }}
      {{- end }}