apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.media.storage | quote }}
  {{- if .Values.media.storageClass }}
  storageClassName: {{ .Values.media.storageClass }}
  {{- end }}
