apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}
        ports:
          - containerPort: {{ .Values.postgres.port }}
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DB_PASSWORD
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
        resources:
          requests:
            memory: {{ .Values.postgres.resources.requests.memory | quote }}
            cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory | quote }}
            cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
