apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.django.secret.secretKey | b64enc | quote }}
  DB_NAME: {{ .Values.django.secret.dbName | b64enc | quote }}
  DB_USER: {{ .Values.django.secret.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.django.secret.dbPassword | b64enc | quote }}
