apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: django
  endpoints:
  - port: web
    path: /django-prometheus/metrics
    interval: 15s
