apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c',
           'until pg_isready -h postgres-service -U $DB_USER;
            do echo "Waiting for PostgreSQL...";
            sleep 2; 
            done;'
          ]
          envFrom:
            - secretRef:
                name: django-secret             
      containers:
      - name: django
        image: subhashdevopslearner/djstack-web:latest
        ports:
          - containerPort: 8000
        command: ["gunicorn"]
        args: ["djstack.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]
        envFrom:
          - configMapRef:
              name: django-config
          - secretRef:
              name: django-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"