apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: subhashdevopslearner/djstack-web:latest
        ports:
          - containerPort: 8000
        command: ["gunicorn"]
        args: ["djstack.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]
        envFrom:
          - configMapRef:
              name: django-config
          - secretRef:
              name: django-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"