# limit-range.yml
apiVersion: v1
kind: LimitRange
metadata:
  name: development-limits
  namespace: development
spec:
  limits:
    - type: Container
      default:                  # default limits if not specified
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:           # default requests if not specified
        cpu: "100m"
        memory: "128Mi"
      max:                      # maximum allowed
        cpu: "500m"
        memory: "512Mi"