name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helmcharts/**' # Triggers only when changes are made to your charts folder

permissions:
  contents: write # Allows the action to write to your gh-pages branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helmcharts # Tells the action where your chart directory lives
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"